version: '3'
services:
  php-apache:
    image: php:8.2-apache
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
  node-app:
    image: devlatest/otivo-dev-app:latest
    working_dir: /usr/src/apps
    volumes:
      - ./vue:/usr/src/apps
    ports:
      - "8080:8080"